pipeline {
    agent any

    stages {
        stage('CleanUp') {
            steps {
                echo 'CleanUp'
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Release') {
            steps {
                echo 'Test'
            }
        }
    }
}
